# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :forwarded_port, guest: 8080, host: 8080

 
  config.vm.provision :chef_solo do |chef| 
     
     chef.json = { "java" => { "jdk_version" => "7", "install_flavor" => "oracle", "oracle" => { "accept_oracle_download_terms" => true}} }

     chef.add_recipe "java"
     chef.add_recipe "scalatra"

  end

end
